# Generated by Django 3.0.4 on 2020-04-02 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estudiante_nivelestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='eMail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='eMail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('eMail', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Barrio')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Institucion')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pais')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
