# Generated by Django 3.0.4 on 2020-04-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200402_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='locacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Locacion'),
            preserve_default=False,
        ),
    ]
