# Generated by Django 3.0.4 on 2020-04-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200403_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='locacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Locacion'),
        ),
    ]
