# Generated by Django 3.0.4 on 2020-04-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200403_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
