# Generated by Django 3.0.4 on 2020-04-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200403_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Locación', 'verbose_name_plural': 'Locaciones'},
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duración', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Institucion')),
                ('locacion', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Locacion')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
    ]
