# Generated by Django 3.0.4 on 2020-04-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='locacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Locacion'),
        ),
        migrations.CreateModel(
            name='RequisitosCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Requisito')),
            ],
            options={
                'verbose_name': 'Requisito cuso',
                'verbose_name_plural': 'Requisitos curso',
                'ordering': ['requisito'],
            },
        ),
    ]
