# Generated by Django 3.0.4 on 2020-04-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200411_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='requisitoscurso',
            options={'ordering': ['requisito'], 'verbose_name': 'Requisito curso', 'verbose_name_plural': 'Requisitos curso'},
        ),
        migrations.CreateModel(
            name='MateriasCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(default=1)),
                ('horas', models.IntegerField(default=0)),
                ('creditos', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Materia')),
            ],
            options={
                'verbose_name': 'Materia curso',
                'verbose_name_plural': 'Materias curso',
                'ordering': ['curso', 'materia', 'semestre'],
            },
        ),
    ]
