# Generated by Django 3.0.4 on 2020-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200413_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duración', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CursoAux',
                'verbose_name_plural': 'CursosAux',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='materiascurso',
            options={'ordering': ['curso'], 'verbose_name': 'Materia curso', 'verbose_name_plural': 'Materias curso'},
        ),
    ]
