# Generated by Django 3.0.4 on 2020-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200417_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoaux',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
