# Generated by Django 3.0.4 on 2020-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cursoaux_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoaux',
            name='idCurso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
